USE BelgiumPopulation
GO
CREATE TABLE FactsBEPop (
[Id_data] int IDENTITY(1,1) CONSTRAINT PK_FactsBEPop PRIMARY KEY,
[CODE INS] int NOT NULL,
[Lieu de résidence] nvarchar(100) NOT NULL,
[Province] nvarchar(100) NOT NULL, 
[Région] nvarchar(100) NOT NULL, 
[Année] smallint NOT NULL, 
[Sexe] nvarchar(15), 
[Belgique] int, 
[Allemagne] int, 
[Autriche] int, 
[Bulgarie] int, 
[Chypre] int, 
[Danemark] int, 
[Espagne] int, 
[Finlande] int, 
[France] int, 
[Royaume-Uni] int, 
[Luxembourg] int, 
[Grèce] int, 
[Hongrie] int, 
[Irlande] int, 
[Malte] int, 
[Portugal] int, 
[Roumanie] int,
[Suède] int,
[Italie] int, 
[Pays-Bas] int, 
[Lettonie] int, 
[Estonie] int, 
[Lituanie] int, 
[Pologne] int, 
[Tchéquie] int, 
[Slovaquie] int, 
[Croatie] int,
[Slovénie] int,
[Albanie] int,
[Norvège] int,
[Suisse] int,
[Serbie/Monténégro/ex-Yougoslavie] int, 
[Bélarus] int, 
[Ukraine] int, 
[Russie] int, 
[Macédoine du Nord] int, 
[Bosnie-Herzégovine] int,
[Monténégro] int,
[Serbie] int,
[Kosovo] int,
[Ex-Yougoslavie] int,
[Ex-Tchécoslovaquie] int,
[Ex-Union Soviétique] int,
[Autres pays d'Europe] int,
[Corée du Sud] int, 
[Inde] int,
[Indonésie] int,
[Japon] int,
[Népal] int,
[Philippines] int,
[Chine] int,
[Vietnam] int,
[Kazakhstan] int,
[Kirghizistan] int,
[Ouzbékistan] int,
[Thaïlande] int,
[Bangladesh] int,
[Arménie] int,
[Azerbaïdjan] int,
[Afghanistan] int,
[Géorgie] int,
[Irak] int,
[Iran] int,
[Israël] int,
[Liban] int,
[Pakistan] int,
[Turquie] int,
[Autres pays d'Asie] int, 
[Burundi] int,
[Cameroun] int,
[Congo-Kinshasha] int,
[Congo-Brazza] int, 
[Côte d'Ivoire] int,
[Bénin] int,
[Éthiopie] int,
[Ghana] int,
[Guinée] int,
[Maurice] int,
[Sénégal] int,
[Niger] int,
[Nigéria] int,
[Afrique Du Sud] int,
[Rwanda] int,
[Sierra Leone] int,
[Somalie] int,
[Togo] int,
[Angola] int,
[Algérie] int,
[Égypte] int,
[Maroc] int,
[Mauritanie] int,
[Tunisie] int,
[Autres pays d'Afrique] int, 
[Canada] int,
[États-Unis] int,
[Cuba] int,
[Mexique] int,
[République Dominicaine] int, 
[Brésil] int,
[Chili] int,
[Colombie] int,
[Équateur] int,
[Pérou] int,
[Autres pays d'Amérique] int,
[Australie] int,
[Autres pays d'Océanie] int,
[Indéterminés/Apatrides] int,
)