USE BelgiumPopulation
GO
CREATE TABLE FactsBEPop (
[Id_data] int IDENTITY(1,1) CONSTRAINT PK_FactsBEPop PRIMARY KEY,
[CODE INS] int NOT NULL,
[Lieu de résidence] nvarchar(100) NOT NULL,
[Province] nvarchar(100) NOT NULL, 
[Région] nvarchar(100) NOT NULL, 
[Année] smallint NOT NULL, 
[Sexe] nvarchar(15), 
[Belgique] int, 
[Allemagne] int, 
[Autriche] int, 
[Bulgarie] int, 
[Chypre] int, 
[Danemark] int, 
[Espagne] int, 
[Finlande] int, 
[France] int, 
[Royaume-Uni] int, 
[Luxembourg] int, 
[Grèce] int, 
[Hongrie] int, 
[Irlande] int, 
[Malte] int, 
[Portugal] int, 
[Roumanie] int,
[Suède] int,
[Italie] int, 
[Pays-Bas] int, 
[Lettonie] int, 
[Estonie] int, 
[Lituanie] int, 
[Pologne] int, 
[Tchéquie] int, 
[Slovaquie] int, 
[Croatie] int,
[Slovénie] int,
[Albanie] int,
[Norvège] int,
[Suisse] int,
[Serbie/Monténégro/ex-Yougoslavie] int, 
[Bélarus] int, 
[Ukraine] int, 
[Russie] int, 
[Macédoine du Nord] int, 
[Bosnie-Herzégovine] int,
[Monténégro] int,
[Serbie] int,
[Kosovo] int,
[Ex-Yougoslavie] int,
[Ex-Tchécoslovaquie] int,
[Ex-Union Soviétique] int,
[Autres pays d'Europe] int,
[Corée du Sud] int, 
[Inde] int,
[Indonésie] int,
[Japon] int,
[Népal] int,
[Philippines] int,
[Chine] int,
[Vietnam] int,
[Kazakhstan] int,
[Kirghizistan] int,
[Ouzbékistan] int,
[Thaïlande] int,
[Bangladesh] int,
[Arménie] int,
[Azerbaïdjan] int,
[Afghanistan] int,
[Géorgie] int,
[Irak] int,
[Iran] int,
[Israël] int,
[Liban] int,
[Pakistan] int,
[Turquie] int,
[Autres pays d'Asie] int, 
[Burundi] int,
[Cameroun] int,
[Congo-Kinshasha] int,
[Congo-Brazza] int, 
[Côte d'Ivoire] int,
[Bénin] int,
[Éthiopie] int,
[Ghana] int,
[Guinée] int,
[Maurice] int,
[Sénégal] int,
[Niger] int,
[Nigéria] int,
[Afrique Du Sud] int,
[Rwanda] int,
[Sierra Leone] int,
[Somalie] int,
[Togo] int,
[Angola] int,
[Algérie] int,
[Égypte] int,
[Maroc] int,
[Mauritanie] int,
[Tunisie] int,
[Autres pays d'Afrique] int, 
[Canada] int,
[États-Unis] int,
[Cuba] int,
[Mexique] int,
[République Dominicaine] int, 
[Brésil] int,
[Chili] int,
[Colombie] int,
[Équateur] int,
[Pérou] int,
[Autres pays d'Amérique] int,
[Australie] int,
[Autres pays d'Océanie] int,
[Indéterminés/Apatrides] int,
)



CREATE TABLE BEGeoTranslations(
[INS-NIS] int NOT NULL,
[Deutsh] nvarchar(75),
[English] nvarchar(75),
[Français] nvarchar(75),
[Nederlands] nvarchar(75),
[Début validité] date,
[Fin validité] date
)


CREATE TABLE BEPopMovement(
[INS-NIS] int NOT NULL,
[Lieu de résidence] nvarchar(100) NOT NULL,
[Année de référence] date NOT NULL, 
[Province] nvarchar(50) NOT NULL, 
[Population totale] int,
[Naissances] int,
[Décès] int,
[Entrées internes] int,
[Sorties internes] int,
[Immigrations] int,
[Changements registre (entrées)] int,
[Réinscriptions] int,
[Émigrations] int,
[Changements de registre (sorties)] int,
[Rayés d'office] int, 
[Ajustement statistique] int,
[Abandons nationalité belge] int,
[Demandes nationalité belge] int
)


CREATE TABLE BEPopAgeGroups(
[INS-NIS] int NOT NULL,
[Lieu de résidence] nvarchar(100) NOT NULL,
[Année de référence] date NOT NULL, 
[Sexe] varchar(1),
[< 5] int,
[5-9] int,
[10-14] int,
[15-19] int,
[20-24] int,
[25-29] int,
[30-34] int,
[35-39] int,
[40-44] int,
[45-49] int,
[50-54] int,
[55-59] int,
[60-64] int,
[65-69] int,
[70-74] int,
[75-79] int,
[80-84] int,
[85-89] int,
[90-94] int,
[95 <] int,
)

